# Generated by Django 5.0.1 on 2025-12-25 05:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('platform', models.CharField(max_length=100)),
                ('architecture', models.CharField(default='x64', max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('offline', 'Offline')], default='active', max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['status', '-last_seen'], name='c2_agents_a_status_4edd9a_idx'), models.Index(fields=['hostname'], name='c2_agents_a_hostnam_6fbce2_idx')],
            },
        ),
    ]
